export const REGISTER_USER_REQUEST ="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS ="REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAIL ="REGISTER_USER_FAIL";

export const LOGIN_USER_REQUEST ="LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS ="LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAIL ="LOGIN_USER_FAIL";

export const AVATAR_USER_REQUEST ="AVATAR_USER_REQUEST";
export const AVATAR_USER_SUCCESS ="AVATAR_USER_SUCCESS";
export const AVATAR_USER_FAIL ="AVATAR_USER_FAIL";

export const ALL_USER_REQUEST ="AVATAR_USER_REQUEST";
export const ALL_USER_SUCCESS ="AVATAR_USER_SUCCESS";
export const ALL_USER_FAIL ="AVATAR_USER_FAIL";